spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rsystem
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
